fix(pytorch_to_onnx.py): fix ValueError
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider',
'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers
parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(...,
providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)